language: node_js
node_js:
  - "node"
env:
  - browser='browserstack:chrome,safari'
  # - EXPORT_COVERAGE=1 CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
